name: Lint extra docsite docs and links
on:
  workflow_call:

jobs:
  docsite:
    name: Lint extra docsite docs and links
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install antsibull-docs
        run: pip install antsibull-docs --disable-pip-version-check

      - name: Run collection docs linter
        run: antsibull-docs lint-collection-docs .
