# Python module release management
name: Release Management

on:
  workflow_call:

env:
  # Python language version to use.
  PYTHON_VERSION: '3.10'

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
    steps:
      - name: DevOpsArrBOT token
        id: DevOpsArrBOT
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: '305652'
          private_key: ${{ secrets.DEVOPSARRBOT_PRIVATE_KEY }}
      - name: app name
        id: app-name
        run: |
          app=${{ github.repository }} &&\
          echo "name=$(echo $app | sed -e 's%.*/%%g' -e 's%-.*%%g')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          # Allow relase please to access older tag information.
          fetch-depth: 0
          token: ${{ steps.DevOpsArrBOT.outputs.token }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Release Please
        id: release_please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          token: ${{ steps.DevOpsArrBOT.outputs.token }}
          extra-files: |
            README.md
            pyproject.toml
            setup.py
            ${{ steps.app-name.outputs.name }}/__init__.py
            ${{ steps.app-name.outputs.name }}/configuration.py
            ${{ steps.app-name.outputs.name }}/api_client.py

  pypi-release:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build requests pydantic
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@36978192ca7715ea2e0d12e82d5518a651a9f739
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

